// GLOBAL
export const EL_REQUEST = 'EL_REQUEST';
export const EL_SUCCESS = 'EL_SUCCESS';
export const EL_FAILURE = 'EL_FAILURE';

export const SEL_REQUEST = 'SEL_REQUEST';
export const SEL_SUCCESS = 'SEL_SUCCESS';
export const SEL_FAILURE = 'SEL_FAILURE';

export const ISAUTHENTICATED_REQUEST = 'ISAUTHENTICATED_REQUEST';
export const ISAUTHENTICATED_SUCCESS = 'ISAUTHENTICATED_SUCCESS';
export const ISAUTHENTICATED_FAILURE = 'ISAUTHENTICATED_FAILURE';

// SHEET
export const GET_SHEET_REQUEST = 'GET_SHEET_REQUEST';
export const GET_SHEET_SUCCESS = 'GET_SHEET_SUCCESS';
export const GET_SHEET_FAILURE = 'GET_SHEET_FAILURE';

// MANAGERS
export const GET_MANAGER_REQUEST = 'GET_MANAGER_REQUEST';
export const GET_MANAGER_SUCCESS = 'GET_MANAGER_SUCCESS';
export const GET_MANAGER_FAILURE = 'GET_MANAGER_FAILURE';


// MT5 SYMBOL CONFIGURATIONS
export const GET_MT5SYMBOLCONFIGURATIONS_REQUEST = 'GET_MT5SYMBOLCONFIGURATIONS_REQUEST';
export const GET_MT5SYMBOLCONFIGURATIONS_SUCCESS = 'GET_MT5SYMBOLCONFIGURATIONS_SUCCESS';
export const GET_MT5SYMBOLCONFIGURATIONS_FAILURE = 'GET_MT5SYMBOLCONFIGURATIONS_FAILURE';

// MT5 SUFFIX
export const GET_MT5SUFFIX_REQUEST = 'GET_MT5SUFFIX_REQUEST';
export const GET_MT5SUFFIX_SUCCESS = 'GET_MT5SUFFIX_SUCCESS';
export const GET_MT5SUFFIX_FAILURE = 'GET_MT5SUFFIX_FAILURE';

// MT5SymbolsConfigurationsAndSuffixes
export const GET_MT5SymbolsConfigurationsAndSuffixes_REQUEST = 'GET_MT5SymbolsConfigurationsAndSuffixes_REQUEST';
export const GET_MT5SymbolsConfigurationsAndSuffixes_SUCCESS = 'GET_MT5SymbolsConfigurationsAndSuffixes_SUCCESS';
export const GET_MT5SymbolsConfigurationsAndSuffixes_FAILURE = 'GET_MT5SymbolsConfigurationsAndSuffixes_FAILURE';

// COVERAGEACCOUNTS
export const GET_COVERAGEACCOUNTS_REQUEST = 'GET_COVERAGEACCOUNTS_REQUEST';
export const GET_COVERAGEACCOUNTS_SUCCESS = 'GET_COVERAGEACCOUNTS_SUCCESS';
export const GET_COVERAGEACCOUNTS_FAILURE = 'GET_COVERAGEACCOUNTS_FAILURE';

// SERVERS
export const GET_SERVERS_REQUEST = 'GET_SERVERS_REQUEST';
export const GET_SERVERS_SUCCESS = 'GET_SERVERS_SUCCESS';
export const GET_SERVERS_FAILURE = 'GET_SERVERS_FAILURE';

// MT5CoverageSymbols
export const GET_MT5COVERAGESYMBOLS_REQUEST = 'GET_MT5COVERAGESYMBOLS_REQUEST';
export const GET_MT5COVERAGESYMBOLS_SUCCESS = 'GET_MT5COVERAGESYMBOLS_SUCCESS';
export const GET_MT5COVERAGESYMBOLS_FAILURE = 'GET_MT5COVERAGESYMBOLS_FAILURE';
