// GLOBAL
export const EL_REQUEST = 'EL_REQUEST';
export const EL_SUCCESS = 'EL_SUCCESS';
export const EL_FAILURE = 'EL_FAILURE';

export const SEL_REQUEST = 'SEL_REQUEST';
export const SEL_SUCCESS = 'SEL_SUCCESS';
export const SEL_FAILURE = 'SEL_FAILURE';

export const ISAUTHENTICATED_REQUEST = 'ISAUTHENTICATED_REQUEST';
export const ISAUTHENTICATED_SUCCESS = 'ISAUTHENTICATED_SUCCESS';
export const ISAUTHENTICATED_FAILURE = 'ISAUTHENTICATED_FAILURE';

// SHEET
export const GET_SHEET_REQUEST = 'GET_SHEET_REQUEST';
export const GET_SHEET_SUCCESS = 'GET_SHEET_SUCCESS';
export const GET_SHEET_FAILURE = 'GET_SHEET_FAILURE';

// MANAGERS
export const GET_MANAGER_REQUEST = 'GET_MANAGER_REQUEST';
export const GET_MANAGER_SUCCESS = 'GET_MANAGER_SUCCESS';
export const GET_MANAGER_FAILURE = 'GET_MANAGER_FAILURE';

// MT5 MANAGERS
export const GET_MT5MANAGER_REQUEST = 'GET_MT5MANAGER_REQUEST';
export const GET_MT5MANAGER_SUCCESS = 'GET_MT5MANAGER_SUCCESS';
export const GET_MT5MANAGER_FAILURE = 'GET_MT5MANAGER_FAILURE';

// MT5 SYMBOL CONFIGURATIONS
export const GET_MT5SYMBOLCONFIGURATIONS_REQUEST = 'GET_MT5SYMBOLCONFIGURATIONS_REQUEST';
export const GET_MT5SYMBOLCONFIGURATIONS_SUCCESS = 'GET_MT5SYMBOLCONFIGURATIONS_SUCCESS';
export const GET_MT5SYMBOLCONFIGURATIONS_FAILURE = 'GET_MT5SYMBOLCONFIGURATIONS_FAILURE';

// MT5 SUFFIX
export const GET_MT5SUFFIX_REQUEST = 'GET_MT5SUFFIX_REQUEST';
export const GET_MT5SUFFIX_SUCCESS = 'GET_MT5SUFFIX_SUCCESS';
export const GET_MT5SUFFIX_FAILURE = 'GET_MT5SUFFIX_FAILURE';



