name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build the app
        env:
          CI: ""
          REACT_APP_API_IP: ${{ secrets.REACT_APP_API_IP }}
          REACT_APP_API_PORT: ${{ secrets.REACT_APP_API_PORT }}
          REACT_APP_WS_IP: ${{ secrets.REACT_APP_WS_IP }}
          REACT_APP_WS_PORT: ${{ secrets.REACT_APP_WS_PORT }}
        run: npm run build

      - name: Deploy the build
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          powershell -Command "Copy-Item -Path 'build\\*' -Destination 'C:\\nginx\\nginx-1.26.0\\apps\\riskman-client\\build' -Recurse -Force"


      # Uncomment if using SSH to deploy
      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
      # - name: SSH to Windows Server
      #   run: |
      #     ssh-keyscan ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
      #     ssh -vvv ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} 'cd C:\\nginx\\nginx-1.26.0\\apps\\riskman-client && build_script.sh'
